# Generated by Django 6.0.1 on 2026-01-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_food_calories_alter_food_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
